### ISSUE TITLE
Is product_id big-endian or little-endian?

### ISSUE THREAD

**Issue by dlenski** [ryanbinns/ttwatch#10]
On my Runner watch, `ttwatch/ttwatch -v` shows `Product ID: 0xe9030000`, which matches the string used to download the firmware files from TomTom's server.

I see from the `get_product_id` code that the response from the device is interpreted as big-endian to get this value.

However, looking at the .ttbin files from my device, I find the value in the `FILE_HEADER.product_id` field as `e9 03`.

````
00000000  20 07 00 01 08 19 e9 03  63 07 ba 54 00 00 00 00  | .......c..T....|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 2d 00 00 00  |............-...|
````

Everything else in the .ttbin file (I think!) is little-endian, and the sequential product ID number makes sense in little-endian form:

````
Runner             = 1001 0x03e9
Multi-Sport        = 1002 0x03ea
Runner Cardio      = ????
Multi-Sport Cardio = 1234 0x04d2
    (according to https://github.com/FluffyKaon/TomTom-ttbin-file-format/blob/master/testfiles/Cycling_09-43-10.ttbin)
````

Is the product ID really little-endian (sequential numbering, small values) or big-endian (32-bit values with zero lower half, as used in the firmware download URLs)?

Maybe I'm just over-thinking this... I was trying to generate "speculative" product IDs while poking around on the TomTom server looking for unknown firmware versions.

**Comment by ryanbinns** [comment]
I noticed the difference as well. However, I don't think the issue is particularly relevant as the product id is of very little use except to download the firmware. I'm not sure why it's in the ttbin file at all, as it's not needed to interpret the data.

As for guessing other product id's, if TomTom is anything like my work, product id's are unique company-wide, no matter what team makes the product, so sequential numbers are often merely coincidental.

Every USB message uses big-endian format, and interpreting the product id like this matches the firmware url, so that's what I'm using. I don't use the ttbin field at all.

Ryan
