### ISSUE TITLE
Does it works for the runner 3

### ISSUE THREAD

**Issue by icefinger** [ryanbinns/ttwatch#101]
Dear developpers,
pretty everything in the title. Iḿ planning to but a tomtom runner 3, but I have only linux and I would like to know first if ttwatch works correctly for linux.

**Comment by KlausKhe** [comment]
Hi icefinger,
I am not the developer but use runner 3 with linux using ttwatch. Actions used so far are downloading activities and setting GPSFix. Works. I initialized the watch via Win10 in a vmware. The only 'issue' I detected so far is that the incorporation of altitude data doesn't work anymore,  see my post before yours. But this is rather due to an out of service side of TomTom and has nothing to do with runner 3.
Cheers,
Klaus

**Comment by icefinger** [comment]
Thanks a lot, it answers my question.
