### ISSUE TITLE
Firmware 1.3.255, R/O no manifest file

### ISSUE THREAD

**Issue by petrkutalek** [ryanbinns/ttwatch#128]
Hi @ryanbinns, I would like to thank you for you efford and nice ttwatch code. I like it. However, my Runner 3 watch runs firmware version 1.3.255. Is there any way I could help you to generate manifest file for this firmware?

**Comment by ryanbinns** [comment]
Generating the manifest is not difficult, but very, very time-consuming. The basic idea is to save a copy of the manifest file (ID 0x00850000), change _**one**_ setting on the watch, get another copy of the manifest file and see what changed between the two. And so on and so forth, for all possible settings and values for each setting. It took me a week or more the first time I did it. Since then I've mainly just looked for new settings and assumed the existing ones are correct unless someone tells me otherwise.

**Comment by petrkutalek** [comment]
@ryanbinns OK, I am going to check it during this weekend and let you know. Please, stand by.
