### ISSUE TITLE
Upload of pre-defined races

### ISSUE THREAD

**Issue by weechatter** [ryanbinns/ttwatch#50]
Hello ryan,

i want to create a race with: http://www.pacecreator.com/index.php

It would be fine to upload the created race to the watch

**Comment by ryanbinns** [comment]
I'll have a look into this when I get some history data on my watch and see what information is actually stored on the watch. My watch died so I just got a new one (fortunately under warranty) and I haven't had a chance to get some data on it yet.

**Comment by weechatter** [comment]
If you need some data from the watch let me know.

**Comment by ryanbinns** [comment]
Ok, I went for a run this afternoon and looked at the data the watch generates for the "race myself" function. Essentially, this should be fairly easy to implement, although to make it simpler and easier, I think I'll implement the race generation completely, rather than loading a file generated by that website. Something like:
```bash
ttwatch --create-continuous-race r,"3km@4:00"
ttwatch --create-continuous-race t,"3km@240s"
ttwatch --create-continuous-race c,"12km/1:00:00"
ttwatch --create-continuous-race f,"2km@3:00,10km@4:00"
```
The first letter of each option value would be the activity type. The first two commands would create the same race (but for different activities), creating a race of 3km at a pace of 4min/km. The third would create a cycling race of 12km in 1hr. The fourth would create a freestyle race of 2km at a pace of 3min/km followed by 10km at 4min/km. How does that sound?

I can't think of a better option name at the moment, but if you have any ideas...

**Comment by ryanbinns** [comment]
I have pushed an update that implements this. Let me know if it works for you. It's basically exactly as I specified above.

**Comment by weechatter** [comment]
Wow! That sounds great. Is there a way  to send you an paypal donation, for a beer for example, ryan? :-)

**Comment by ryanbinns** [comment]
Thanks for the thought, but no, that's ok. I don't drink anyway ;-)

**Comment by weechatter** [comment]
Only one question Ryan. Is there any limitation in this function for <distance/time> / <distance>@<pace>
or is it possible to create a race with 21 or even 42 values?

**Comment by ryanbinns** [comment]
No, there's no limitation. It will keep on extending the race for as long as there are values left in the string.

**Comment by weechatter** [comment]
Thanks. So the only limitation is the watch itself and i guess only TomTom knows how many values are possible.
