### ISSUE TITLE
Support for managing Music on devices with that functionality.

### ISSUE THREAD

**Issue by tealeg** [ryanbinns/ttwatch#99]
Hi, are there any current plans to support putting music on the newer devices with that function (and removing it, I suppose) ?

**Comment by ryanbinns** [comment]
No, not at the moment. AFAIK, music is transferred using a mass-storage device, and there is little reason for me to include that functionality since Linux supports mass-storage devices natively anyway. I don't have a device with music functionality either, so that would make it a little difficult for me.

**Comment by tealeg** [comment]
@ryanbinns thanks!  Mass storage would be great.  I think I might take  punt on one if the rest of the functionality works.
